#!/usr/bin/env python3
import os
import json
import requests
import subprocess

def main():
    # Get app spec
    app_spec = json.loads(os.environ.get('APP_SPEC', '{}'))
    
    print("Generating app code for:", app_spec.get('app_name'))
    
    # Call AI to generate actual code
    # This runs on GitHub's servers, not your phone!
    openrouter_key = os.environ.get('OPENROUTER_API_KEY')
    
    if openrouter_key:
        prompt = f"Generate complete React Native app with: {json.dumps(app_spec)}"
        
        # Call AI (on GitHub's internet, not yours!)
        response = requests.post(
            "https://openrouter.ai/api/v1/chat/completions",
            headers={"Authorization": f"Bearer {openrouter_key}", "Content-Type": "application/json"},
            json={"model": "deepseek/deepseek-r1", "messages": [{"role": "user", "content": prompt}]}
        )
        
        code = response.json()["choices"][0]["message"]["content"]
        
        # Save generated code
        with open("generated_app.js", "w") as f:
            f.write(code)
        
        print("✅ Code generated by AI in cloud!")
    else:
        print("⚠️ No API key, using template")
        with open("generated_app.js", "w") as f:
            f.write("// AI-generated app code would be here")

if __name__ == "__main__":
    main()
